### ISSUE TITLE
omnibus 3.2.2 reports "undefined method `make` for #<Omnibus::Builder(Cleanroom)>"

### ISSUE THREAD

**Issue by chenyun** [chef/omnibus#398]
codes in config/software/nginx.rb of omnibus-software

``` ruby
   make "-j #{workers} install"
```

But it works fine with 4.0.0.rc.2.
